### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by G3ZZING** [Fweak/Bypass-Block-Message#2]
@Fweak The bot is perfectly working, but I send a message to a blocked user, however, automatically ... it didn't send anything to the user, and it didn't show any error in the terminal. and now?

**Comment by Fweak** [comment]
If the user of which you want to send a message to, blocks you then the script doesn't work and it outputs "Error [something]..." in console. If you block the user and they block you aswell then it won't work. Only works if you only blocked the user.
